@startuml
[*] --> Welcome

state MainMenu {
  state "Weather Report" as WeatherReport
  state "Seasonal Weather Patterns" as SeasonalPatterns
  state "Planting Suggestion" as PlantingSuggestion
  state "Local Rainfall" as LocalRainfall
  state "Indigenous Knowledge" as IndigenousKnowledge
  state "Agricultural Knowledge" as AgriculturalKnowledge
  state "Alert Subscription" as AlertSubscription
}

Welcome --> MainMenu : Language Selected

MainMenu --> WeatherReport : Press 1
MainMenu --> SeasonalPatterns : Press 2
MainMenu --> PlantingSuggestion : Press 3
MainMenu --> LocalRainfall : Press 4
MainMenu --> IndigenousKnowledge : Press 5
MainMenu --> AgriculturalKnowledge : Press 6
MainMenu --> AlertSubscription : Press 7
MainMenu --> MainMenu : Press 0 (Repeat)

WeatherReport --> MainMenu : After Selection
SeasonalPatterns --> MainMenu
PlantingSuggestion --> MainMenu
LocalRainfall --> MainMenu
IndigenousKnowledge --> MainMenu
AgriculturalKnowledge --> MainMenu
AlertSubscription --> MainMenu
@enduml
